/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TopicsRouteImport } from './routes/topics'
import { Route as RequestObjectRouteImport } from './routes/request-object'
import { Route as MeRouteImport } from './routes/me'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as DiscussionsRouteImport } from './routes/discussions'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ObjectsIndexRouteImport } from './routes/objects.index'
import { Route as ArchiveIndexRouteImport } from './routes/archive.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TopicsTagRouteImport } from './routes/topics.$tag'
import { Route as SubmitObjectIdRouteImport } from './routes/submit.$objectId'
import { Route as ObjectsIdRouteImport } from './routes/objects.$id'
import { Route as ArchiveEvidenceRouteImport } from './routes/archive.evidence'
import { Route as ArchiveCaseCodeRouteImport } from './routes/archive.$caseCode'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTemperatureRouteImport } from './routes/admin.temperature'
import { Route as AdminRequestsRouteImport } from './routes/admin.requests'
import { Route as AdminObservationsRouteImport } from './routes/admin.observations'
import { Route as AdminObjectsRouteImport } from './routes/admin.objects'
import { Route as AdminKnowledgeRouteImport } from './routes/admin.knowledge'
import { Route as AdminCommentsRouteImport } from './routes/admin.comments'
import { Route as AdminBulkImportRouteImport } from './routes/admin.bulk-import'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'

const TopicsRoute = TopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestObjectRoute = RequestObjectRouteImport.update({
  id: '/request-object',
  path: '/request-object',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscussionsRoute = DiscussionsRouteImport.update({
  id: '/discussions',
  path: '/discussions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectsIndexRoute = ObjectsIndexRouteImport.update({
  id: '/objects/',
  path: '/objects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveIndexRoute = ArchiveIndexRouteImport.update({
  id: '/archive/',
  path: '/archive/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TopicsTagRoute = TopicsTagRouteImport.update({
  id: '/$tag',
  path: '/$tag',
  getParentRoute: () => TopicsRoute,
} as any)
const SubmitObjectIdRoute = SubmitObjectIdRouteImport.update({
  id: '/submit/$objectId',
  path: '/submit/$objectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectsIdRoute = ObjectsIdRouteImport.update({
  id: '/objects/$id',
  path: '/objects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveEvidenceRoute = ArchiveEvidenceRouteImport.update({
  id: '/archive/evidence',
  path: '/archive/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveCaseCodeRoute = ArchiveCaseCodeRouteImport.update({
  id: '/archive/$caseCode',
  path: '/archive/$caseCode',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTemperatureRoute = AdminTemperatureRouteImport.update({
  id: '/temperature',
  path: '/temperature',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRequestsRoute = AdminRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminObservationsRoute = AdminObservationsRouteImport.update({
  id: '/observations',
  path: '/observations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminObjectsRoute = AdminObjectsRouteImport.update({
  id: '/objects',
  path: '/objects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKnowledgeRoute = AdminKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommentsRoute = AdminCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBulkImportRoute = AdminBulkImportRouteImport.update({
  id: '/bulk-import',
  path: '/bulk-import',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/discussions': typeof DiscussionsRoute
  '/feed': typeof FeedRoute
  '/knowledge': typeof KnowledgeRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/request-object': typeof RequestObjectRoute
  '/topics': typeof TopicsRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/bulk-import': typeof AdminBulkImportRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/knowledge': typeof AdminKnowledgeRoute
  '/admin/objects': typeof AdminObjectsRoute
  '/admin/observations': typeof AdminObservationsRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/temperature': typeof AdminTemperatureRoute
  '/admin/users': typeof AdminUsersRoute
  '/archive/$caseCode': typeof ArchiveCaseCodeRoute
  '/archive/evidence': typeof ArchiveEvidenceRoute
  '/objects/$id': typeof ObjectsIdRoute
  '/submit/$objectId': typeof SubmitObjectIdRoute
  '/topics/$tag': typeof TopicsTagRoute
  '/admin/': typeof AdminIndexRoute
  '/archive/': typeof ArchiveIndexRoute
  '/objects/': typeof ObjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/discussions': typeof DiscussionsRoute
  '/feed': typeof FeedRoute
  '/knowledge': typeof KnowledgeRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/request-object': typeof RequestObjectRoute
  '/topics': typeof TopicsRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/bulk-import': typeof AdminBulkImportRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/knowledge': typeof AdminKnowledgeRoute
  '/admin/objects': typeof AdminObjectsRoute
  '/admin/observations': typeof AdminObservationsRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/temperature': typeof AdminTemperatureRoute
  '/admin/users': typeof AdminUsersRoute
  '/archive/$caseCode': typeof ArchiveCaseCodeRoute
  '/archive/evidence': typeof ArchiveEvidenceRoute
  '/objects/$id': typeof ObjectsIdRoute
  '/submit/$objectId': typeof SubmitObjectIdRoute
  '/topics/$tag': typeof TopicsTagRoute
  '/admin': typeof AdminIndexRoute
  '/archive': typeof ArchiveIndexRoute
  '/objects': typeof ObjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/discussions': typeof DiscussionsRoute
  '/feed': typeof FeedRoute
  '/knowledge': typeof KnowledgeRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/request-object': typeof RequestObjectRoute
  '/topics': typeof TopicsRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/bulk-import': typeof AdminBulkImportRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/knowledge': typeof AdminKnowledgeRoute
  '/admin/objects': typeof AdminObjectsRoute
  '/admin/observations': typeof AdminObservationsRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/temperature': typeof AdminTemperatureRoute
  '/admin/users': typeof AdminUsersRoute
  '/archive/$caseCode': typeof ArchiveCaseCodeRoute
  '/archive/evidence': typeof ArchiveEvidenceRoute
  '/objects/$id': typeof ObjectsIdRoute
  '/submit/$objectId': typeof SubmitObjectIdRoute
  '/topics/$tag': typeof TopicsTagRoute
  '/admin/': typeof AdminIndexRoute
  '/archive/': typeof ArchiveIndexRoute
  '/objects/': typeof ObjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/discussions'
    | '/feed'
    | '/knowledge'
    | '/login'
    | '/me'
    | '/request-object'
    | '/topics'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/bulk-import'
    | '/admin/comments'
    | '/admin/knowledge'
    | '/admin/objects'
    | '/admin/observations'
    | '/admin/requests'
    | '/admin/temperature'
    | '/admin/users'
    | '/archive/$caseCode'
    | '/archive/evidence'
    | '/objects/$id'
    | '/submit/$objectId'
    | '/topics/$tag'
    | '/admin/'
    | '/archive/'
    | '/objects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/discussions'
    | '/feed'
    | '/knowledge'
    | '/login'
    | '/me'
    | '/request-object'
    | '/topics'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/bulk-import'
    | '/admin/comments'
    | '/admin/knowledge'
    | '/admin/objects'
    | '/admin/observations'
    | '/admin/requests'
    | '/admin/temperature'
    | '/admin/users'
    | '/archive/$caseCode'
    | '/archive/evidence'
    | '/objects/$id'
    | '/submit/$objectId'
    | '/topics/$tag'
    | '/admin'
    | '/archive'
    | '/objects'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/discussions'
    | '/feed'
    | '/knowledge'
    | '/login'
    | '/me'
    | '/request-object'
    | '/topics'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/bulk-import'
    | '/admin/comments'
    | '/admin/knowledge'
    | '/admin/objects'
    | '/admin/observations'
    | '/admin/requests'
    | '/admin/temperature'
    | '/admin/users'
    | '/archive/$caseCode'
    | '/archive/evidence'
    | '/objects/$id'
    | '/submit/$objectId'
    | '/topics/$tag'
    | '/admin/'
    | '/archive/'
    | '/objects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  DiscussionsRoute: typeof DiscussionsRoute
  FeedRoute: typeof FeedRoute
  KnowledgeRoute: typeof KnowledgeRoute
  LoginRoute: typeof LoginRoute
  MeRoute: typeof MeRoute
  RequestObjectRoute: typeof RequestObjectRoute
  TopicsRoute: typeof TopicsRouteWithChildren
  ArchiveCaseCodeRoute: typeof ArchiveCaseCodeRoute
  ArchiveEvidenceRoute: typeof ArchiveEvidenceRoute
  ObjectsIdRoute: typeof ObjectsIdRoute
  SubmitObjectIdRoute: typeof SubmitObjectIdRoute
  ArchiveIndexRoute: typeof ArchiveIndexRoute
  ObjectsIndexRoute: typeof ObjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/topics': {
      id: '/topics'
      path: '/topics'
      fullPath: '/topics'
      preLoaderRoute: typeof TopicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-object': {
      id: '/request-object'
      path: '/request-object'
      fullPath: '/request-object'
      preLoaderRoute: typeof RequestObjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discussions': {
      id: '/discussions'
      path: '/discussions'
      fullPath: '/discussions'
      preLoaderRoute: typeof DiscussionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objects/': {
      id: '/objects/'
      path: '/objects'
      fullPath: '/objects/'
      preLoaderRoute: typeof ObjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive/': {
      id: '/archive/'
      path: '/archive'
      fullPath: '/archive/'
      preLoaderRoute: typeof ArchiveIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/topics/$tag': {
      id: '/topics/$tag'
      path: '/$tag'
      fullPath: '/topics/$tag'
      preLoaderRoute: typeof TopicsTagRouteImport
      parentRoute: typeof TopicsRoute
    }
    '/submit/$objectId': {
      id: '/submit/$objectId'
      path: '/submit/$objectId'
      fullPath: '/submit/$objectId'
      preLoaderRoute: typeof SubmitObjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objects/$id': {
      id: '/objects/$id'
      path: '/objects/$id'
      fullPath: '/objects/$id'
      preLoaderRoute: typeof ObjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive/evidence': {
      id: '/archive/evidence'
      path: '/archive/evidence'
      fullPath: '/archive/evidence'
      preLoaderRoute: typeof ArchiveEvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive/$caseCode': {
      id: '/archive/$caseCode'
      path: '/archive/$caseCode'
      fullPath: '/archive/$caseCode'
      preLoaderRoute: typeof ArchiveCaseCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/temperature': {
      id: '/admin/temperature'
      path: '/temperature'
      fullPath: '/admin/temperature'
      preLoaderRoute: typeof AdminTemperatureRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/requests': {
      id: '/admin/requests'
      path: '/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AdminRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/observations': {
      id: '/admin/observations'
      path: '/observations'
      fullPath: '/admin/observations'
      preLoaderRoute: typeof AdminObservationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/objects': {
      id: '/admin/objects'
      path: '/objects'
      fullPath: '/admin/objects'
      preLoaderRoute: typeof AdminObjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/knowledge': {
      id: '/admin/knowledge'
      path: '/knowledge'
      fullPath: '/admin/knowledge'
      preLoaderRoute: typeof AdminKnowledgeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/comments': {
      id: '/admin/comments'
      path: '/comments'
      fullPath: '/admin/comments'
      preLoaderRoute: typeof AdminCommentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bulk-import': {
      id: '/admin/bulk-import'
      path: '/bulk-import'
      fullPath: '/admin/bulk-import'
      preLoaderRoute: typeof AdminBulkImportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBulkImportRoute: typeof AdminBulkImportRoute
  AdminCommentsRoute: typeof AdminCommentsRoute
  AdminKnowledgeRoute: typeof AdminKnowledgeRoute
  AdminObjectsRoute: typeof AdminObjectsRoute
  AdminObservationsRoute: typeof AdminObservationsRoute
  AdminRequestsRoute: typeof AdminRequestsRoute
  AdminTemperatureRoute: typeof AdminTemperatureRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminBulkImportRoute: AdminBulkImportRoute,
  AdminCommentsRoute: AdminCommentsRoute,
  AdminKnowledgeRoute: AdminKnowledgeRoute,
  AdminObjectsRoute: AdminObjectsRoute,
  AdminObservationsRoute: AdminObservationsRoute,
  AdminRequestsRoute: AdminRequestsRoute,
  AdminTemperatureRoute: AdminTemperatureRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface TopicsRouteChildren {
  TopicsTagRoute: typeof TopicsTagRoute
}

const TopicsRouteChildren: TopicsRouteChildren = {
  TopicsTagRoute: TopicsTagRoute,
}

const TopicsRouteWithChildren =
  TopicsRoute._addFileChildren(TopicsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  DiscussionsRoute: DiscussionsRoute,
  FeedRoute: FeedRoute,
  KnowledgeRoute: KnowledgeRoute,
  LoginRoute: LoginRoute,
  MeRoute: MeRoute,
  RequestObjectRoute: RequestObjectRoute,
  TopicsRoute: TopicsRouteWithChildren,
  ArchiveCaseCodeRoute: ArchiveCaseCodeRoute,
  ArchiveEvidenceRoute: ArchiveEvidenceRoute,
  ObjectsIdRoute: ObjectsIdRoute,
  SubmitObjectIdRoute: SubmitObjectIdRoute,
  ArchiveIndexRoute: ArchiveIndexRoute,
  ObjectsIndexRoute: ObjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
