// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

type SupabaseRuntimeConfig = { url?: string; anonKey?: string };

declare global {
  interface Window {
    __FF_SUPABASE_CONFIG__?: SupabaseRuntimeConfig;
  }
}

function readEnv(name: string): string | undefined {
  const viteEnv = (import.meta as unknown as { env?: Record<string, string | undefined> }).env;
  const procEnv =
    typeof process !== "undefined" && process?.env
      ? (process.env as Record<string, string | undefined>)
      : undefined;
  return viteEnv?.[name] || procEnv?.[name];
}

function readPublicSupabase(): SupabaseRuntimeConfig {
  const runtime = typeof window !== "undefined" ? window.__FF_SUPABASE_CONFIG__ : undefined;
  const url = runtime?.url || readEnv("VITE_SUPABASE_URL") || readEnv("SUPABASE_URL");
  const anonKey =
    runtime?.anonKey ||
    readEnv("VITE_SUPABASE_PUBLISHABLE_KEY") ||
    readEnv("SUPABASE_PUBLISHABLE_KEY") ||
    readEnv("VITE_SUPABASE_ANON_KEY") ||
    readEnv("SUPABASE_ANON_KEY");
  return { url, anonKey };
}

export function hasPublicSupabaseConfig() {
  const { url, anonKey } = readPublicSupabase();
  return Boolean(url && anonKey);
}

function createSupabaseClient() {
  const { url: SUPABASE_URL, anonKey: SUPABASE_PUBLISHABLE_KEY } = readPublicSupabase();

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
